site_name: Teselas Vectoriales en la IDE
theme:
  name: 'material'
  language: 'es'
markdown_extensions:
  - codehilite:
      linenums: True
  - admonition
  - pymdownx.magiclink
  - pymdownx.superfences
repo_url: "https://github.com/geomatico/taller-vt-jiide"
pages:
- Home: index.md
- 1. Qué son: 01_que_son.md
- 2. Cómo crearlas: 02_crearlas.md
- 3. Cómo servirlas: 03_servirlas.md
- 4. Servicios estándar: 04_OGC.md
- 5. Iconos y tipografías: 05_sprites_glyphs.md
- 6. Cómo simbolizarlas: 06_estilos.md
- 7. Cómo visualizarlas: 07_visores.md
- 8. Recursos: 08_recursos.md
